### ISSUE TITLE
Missing shipping cost

### ISSUE THREAD

**Issue by YellowFish085** [Prometee/SyliusPayumStripeCheckoutSessionPlugin#1]
- Sylius: v1.7.3
- SyliusPayumStripeCheckoutSessionPlugin: v1.1 (fresh install)

Hello,

I am trying to use this package in a project and I have a few difficulties with shipping cost: it appears that the shipping cost is not included in the amount to pay when the user is sent to the Stripe payment page.

I have a simple usecase where the user adds an item in the cart that costs 300€ and selects a shipping methods that costs 70€. The order amount is 370€, but when the user is sent to the Stripe payment page the shipping cost is not included in the request made to `/v1/checkout/sessions` and because of that the price to pay for is only 300€.

Still, when I look at the order from the user dashboard or the admin, the shipping cost _is_ included in the displayed payment:

![Screenshot 2020-04-30 at 15 18 36](https://user-images.githubusercontent.com/11556009/80714943-ee6d9100-8af5-11ea-9324-c7c18ff12625.png)

Looking at the code of [DetailsProvider](https://github.com/Prometee/SyliusPayumStripeCheckoutSessionPlugin/blob/master/src/Provider/DetailsProvider.php#L33) and the other providers in the directory, I don't find any place where the shipping cost would be indeed included when the request is created, so I'm assuming that it's just missing from it?

Do we need to override the [DetailsProvider `getDetails` method](https://github.com/Prometee/SyliusPayumStripeCheckoutSessionPlugin/blob/master/src/Provider/DetailsProvider.php#L33) in order to include the shipping cost as an item in the `line_items` array? Something like

```JSON
{
      "amount": "700",
      "currency": "EUR",
      "name": "Shipping",
      "quantity": "1",
}
```

Thank you for you help.

**Comment by AlexandrePavy** [comment]
Hello, i confirm the bug,

as a workaround (i'm not sure about right fix for PR) you can :

Override `\Prometee\SyliusPayumStripeCheckoutSessionPlugin\Provider\LineItemsProvider` with creating `\App\Provider\LineItemsProvider` like this : 

```php
<?php

declare(strict_types=1);

namespace App\Provider;

use Prometee\SyliusPayumStripeCheckoutSessionPlugin\Provider\LineItemProviderInterface;
use Prometee\SyliusPayumStripeCheckoutSessionPlugin\Provider\LineItemsProviderInterface;
use Sylius\Component\Core\Model\OrderInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

final class LineItemsProvider implements LineItemsProviderInterface
{
    /** @var LineItemProviderInterface */
    private $lineItemProvider;

    /** @var TranslatorInterface */
    private $translator;

    public function __construct(
        LineItemProviderInterface $lineItemProvider,
        TranslatorInterface $translator
    ) {
        $this->lineItemProvider = $lineItemProvider;
        $this->translator = $translator;
    }

    /**
     * {@inheritdoc}
     */
    public function getLineItems(OrderInterface $order): ?array
    {
        $lineItems = [];
        foreach ($order->getItems() as $orderItem) {
            $lineItem = $this->lineItemProvider->getLineItem($orderItem);
            if (null !== $lineItem) {
                $lineItems[] = $lineItem;
            }
        }

        if ($order->getShippingTotal() > 0) {
            $lineItems[] = [
                'amount' => $order->getShippingTotal(),
                'currency' => $order->getCurrencyCode(),
                'name' => $this->translator->trans('sylius.ui.shipping_charges'),
                'quantity' => 1,
            ];
        }

        return $lineItems;
    }
}
```

and inside `services.yaml` add :

```yaml
    App\Provider\LineItemsProvider:
        arguments:
            $lineItemProvider: '@prometee.sylius_payum_stripe_checkout_session.provider.line_item'
            $translator: '@translator'
        decorates: 'prometee.sylius_payum_stripe_checkout_session.provider.line_items'
```

Best regards,

**Comment by Prometee** [comment]
Sorry for this late answer @YellowFish085 @AlexandrePavy is right there is definitively something happening with shipping cost. @AlexandrePavy now I understand your PR, I will take care of it quickly.

**Comment by Prometee** [comment]
@YellowFish085 I just fixe this issue adding 2 more `Providers` taking care of :

1. the shipping item (amount and quantity)
2. the shipping line item name

I'm pushing a new release right now.

Sorry again I miss the notification of your issue...
