### ISSUE TITLE
Multiple errors from Stripe WebhookEvent

### ISSUE THREAD

**Issue by Lowcost-dev** [Prometee/SyliusPayumStripeCheckoutSessionPlugin#4]
Hello,

I don't know if it's really a problem but my monolog is configured in order to send me the critical exception. And these days after have installed the Stripe plugin I'm getting these errors (multiple times in a day) :

`RequestNotSupportedException: "Request WebhookEvent{model: EventWrapper} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.`

`LogicException: "The token 06wCxxxxxxzqTUEKs could not be found"`
it's happen without using my sylius shop (hidden website).

I understand the first one, which means than Stripe sent me a request with an unknown event and the plugin cannot handle it.
But for the second one, I don't really know what's the problem. 

There's a way to fix them ? I would like to have some tips/informations 
Else I did a test payment which was working fine. 

Thank you

**Comment by Prometee** [comment]
@Lowcost-dev hello,

First make sure you are using the latest version of this plugin, I made some updates about this Exception some weeks ago to allow third party `Action` to be able to handle the webhook event when it is not supported. https://github.com/Prometee/PayumStripe/blob/4287e8535de0eb85c384652a7feed88dd2603d11/src/Action/Api/WebhookEvent/AbstractPaymentAction.php#L47

But here is the meaning of this error : the payment token `06wCxxxxxxzqTUEKs` is not retrievable in the database table `sylius_payment_security_token` so the process trying to handle it can't get the related `Payment` from this token. Maybe you are using the same api credentials for both of your dev and prod environments. Make sure you are handling dev env payments with Stripe test API credentials and prod/staging env payments with some other Stripe API credentials.

**Comment by Lowcost-dev** [comment]
I'm using the latest version (1.1.2). It should not throw it, right ?

Else for the second one, I directly tried through the prod env. And I've used both (Stripe test/prod credentials) onto my prod env. I've split them in 2 gateway. 
I did some test payment using the stripe test credentials. It works fine.
I've disabled this one and have enabled the gateway which have the stripe prod credentials.

I've removed my Webhook and created a new one, I'll see if this happen again. And try to understand why.
Thanks for your information, I'll back to you if something weird happen.

**Comment by Prometee** [comment]
I'm also monitoring errors thanks to Sentry.io and the Stripe logs. After 1K payments among subscriptions and normal payments there is no error.

Maybe some explanations are needed to understand those kind of error, I was thinking about opening a FAQ.
