### ISSUE TITLE
Gateway "stripe_checkout_session" does not exist

### ISSUE THREAD

**Issue by juferchaud** [Prometee/SyliusPayumStripeCheckoutSessionPlugin#6]
Hello @Prometee you have done a great job, thanks 👍 

Payment with Stripe works well, in dev mode.
But i am facing an issue on incoming webhooks :  `500 - Gateway "stripe_checkout_session" does not exist`

My payment method followed the documentation provided with the lib :

- **code** _stripe_session_checkout_with_sca_
- **gateway** _stripe_checkout_session_

I am confused with the gateway name `stripe_checkout_session`, in database (table `sylius_gateway_config`) it sounds different : 

- **gateway_name** _stripe_session_checkout_with_sca_
- **factory** _stripe_checkout_session_

I would appreciate some help 😉 

### versions
sylius/sylius **v1.7.0**
prometee/payum-stripe                                                      **v1.1.1** 
prometee/payum-stripe-checkout-session-bundle           **v1.1.0**
prometee/sylius-payum-stripe-checkout-session-plugin **v1.1.2**

**Comment by Prometee** [comment]
@juferchaud indeed this need an explanation, the `code` used by Sylius to create a `PaymentMethod` is also used as the `gateway_name`. So the URL for the webhook should be :
`http://localhost/payment/notify/unsafe/stripe_checkout_session_sca` in your case.

Maybe the README should warn about this or ask to put the right `gateway_name ` available in the `sylius_gateway_config` table.

**Comment by juferchaud** [comment]
Thanks for your answer, webhook works fine now 👍
