### ISSUE TITLE
Send order ID in metadata?

### ISSUE THREAD

**Issue by pcmsystemsltd** [Prometee/SyliusPayumStripeCheckoutSessionPlugin#8]
Would it be possible to send the Sylius order ID to Stripe in the metadata? I note this isn't a bug as such, but it would make it a lot easier to cross reference the Stripe payment with the Sylius admin screens (and also the email sent by Stripe notifying of a new payment includes the metadata, currently just showing `token_hash`)

**Comment by Prometee** [comment]
Hello @pcmsystemsltd, the purpose of this plugin is to give the basic way of handling payment through Stripe Checkout Session, letting full customisation available.

You are able to add as many metadata you need decorating the `DetailProvider` by adding it to the checkout array model or to the embed model array such as payment_intent_data metadata for example.

This need a little doc I guess.

**Comment by pcmsystemsltd** [comment]
Thanks for your reply. We'll look at the `DetailProvider` to add it into our metadata. Thanks for your work on the plugin.

**Comment by Prometee** [comment]
@pcmsystemsltd thank you too for this issue, it allow me to understand other usages too 😉
