### ISSUE TITLE
Invalid email causes crash

### ISSUE THREAD

**Issue by ad3m3r5** [Prometee/SyliusPayumStripeCheckoutSessionPlugin#9]
- Sylius: v1.7.0
- SyliusPayumStripeCheckoutSessionPlugin: v1.1

Occurs when the billing page allows an invalid email to be input, such as "test@test". This causes the Stripe API to reject the payment, which in turn causes the crash.

### Email Entered
![image](https://user-images.githubusercontent.com/11009228/90600808-34de1d00-e1c5-11ea-9668-1f1ba7c37e88.png)

### Error In Log
 `request.CRITICAL: Uncaught PHP Exception Stripe\Exception\InvalidRequestException: "Invalid email address: test@test" at /var/www/sylius/vendor/stripe/stripe-php/lib/Exception/ApiErrorException.php line 38 {"exception":"[object] (Stripe\\Exception\\InvalidRequestException(code: 0): Invalid email address: test@test at /var/www/sylius/vendor/stripe/stripe-php/lib/Exception/ApiErrorException.php:38)"} []`

### Error Message In Browser
![image](https://user-images.githubusercontent.com/11009228/90601060-93a39680-e1c5-11ea-80eb-13548132bef3.png)

Is there a way to mitigate this. Such as using regex to validate an email like Stripe would. Or on error, return to the payment page with an error message?

**Comment by Prometee** [comment]
Hello @ad3m3r5,

Do you change the default validator of Sylius ? The email is validated against the EmailValidator of Symfony from what I remember. Maybe their is some alterations there causing later the exception you pointed out.

**Comment by ad3m3r5** [comment]
I haven't touched any validation stuff. I thought it was kinda odd that it didn't pick that issue up.

**Comment by ad3m3r5** [comment]
Based on the symfony docs, there are 3 modes for the emailValidator (strict, loose, html5). All three seem as though they would catch something like "test@test", since it does not contain a valid domain name.

https://symfony.com/doc/current/reference/constraints/Email.html#mode

**Comment by Prometee** [comment]
Here is the validator used : https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CustomerBundle/Resources/config/validation/Customer.xml

It seems that the strict mode allow `test@test`, maybe changing to another can fit your need.

**Comment by ad3m3r5** [comment]
Thanks. I'll be testing out some regex patterns.

https://symfony.com/doc/current/reference/constraints/Regex.html
